import type { ForceGraphData } from "@/types/graph";

/**
 * Sample knowledge graph data for demo/offline mode.
 * Represents entities extracted from the healthcare + GraphRAG corpus.
 */
export const SAMPLE_GRAPH_DATA: ForceGraphData = {
  nodes: [
    {
      id: "graphrag",
      label: "GraphRAG",
      type: "technology",
      description:
        "Graph-based retrieval augmented generation combining vector search with knowledge graph traversal",
      source_document: "01_graphrag_overview.txt",
      highlighted: false,
      val: 18,
    },
    {
      id: "vector_rag",
      label: "Vector RAG",
      type: "technology",
      description:
        "Traditional retrieval augmented generation using semantic vector similarity",
      source_document: "01_graphrag_overview.txt",
      highlighted: false,
      val: 12,
    },
    {
      id: "knowledge_graph",
      label: "Knowledge Graph",
      type: "concept",
      description:
        "Structured representation of entities and relationships extracted from documents",
      source_document: "01_graphrag_overview.txt",
      highlighted: false,
      val: 16,
    },
    {
      id: "hallucination",
      label: "LLM Hallucination",
      type: "concept",
      description:
        "When language models generate plausible but factually incorrect statements",
      source_document: "07_llm_hallucination_enterprise.txt",
      highlighted: false,
      val: 14,
    },
    {
      id: "citation_grounding",
      label: "Citation Grounding",
      type: "concept",
      description:
        "Techniques that anchor AI outputs to verifiable source evidence",
      source_document: "05_citation_grounded_ai.txt",
      highlighted: false,
      val: 15,
    },
    {
      id: "entity_extraction",
      label: "Entity Extraction",
      type: "technology",
      description:
        "NLP pipeline for identifying entities and relationships from text",
      source_document: "04_entity_extraction_nlp.txt",
      highlighted: false,
      val: 11,
    },
    {
      id: "community_detection",
      label: "Community Detection",
      type: "technology",
      description:
        "Algorithms that group densely connected entities into semantic clusters",
      source_document: "09_community_detection.txt",
      highlighted: false,
      val: 10,
    },
    {
      id: "leiden_algorithm",
      label: "Leiden Algorithm",
      type: "technology",
      description:
        "Community detection method guaranteeing internally connected communities",
      source_document: "09_community_detection.txt",
      highlighted: false,
      val: 8,
    },
    {
      id: "neo4j",
      label: "Neo4j",
      type: "technology",
      description:
        "Dominant graph database with Cypher query language and native vector search",
      source_document: "06_graph_databases_ai.txt",
      highlighted: false,
      val: 10,
    },
    {
      id: "lightrag",
      label: "LightRAG",
      type: "technology",
      description:
        "Lightweight GraphRAG implementation with in-memory graph and JSON persistence",
      source_document: "06_graph_databases_ai.txt",
      highlighted: false,
      val: 9,
    },
    {
      id: "eu_ai_act",
      label: "EU AI Act",
      type: "regulation",
      description:
        "First comprehensive regulatory framework for AI requiring transparency and traceability",
      source_document: "10_eu_ai_act_compliance.txt",
      highlighted: false,
      val: 13,
    },
    {
      id: "vaers",
      label: "VAERS",
      type: "organization",
      description:
        "Vaccine Adverse Event Reporting System maintained by CDC and FDA",
      source_document: "03_vaccine_safety_monitoring.txt",
      highlighted: false,
      val: 9,
    },
    {
      id: "vaccine_safety",
      label: "Vaccine Safety Monitoring",
      type: "concept",
      description:
        "Pharmacovigilance systems for detecting adverse events following vaccination",
      source_document: "03_vaccine_safety_monitoring.txt",
      highlighted: false,
      val: 12,
    },
    {
      id: "clinical_trials",
      label: "Clinical Trials",
      type: "concept",
      description:
        "Structured medical research studies evaluating interventions",
      source_document: "11_clinical_trials_ai.txt",
      highlighted: false,
      val: 11,
    },
    {
      id: "umls",
      label: "UMLS",
      type: "technology",
      description:
        "Unified Medical Language System with 4.4M concepts and 16M relationships",
      source_document: "02_knowledge_graphs_healthcare.txt",
      highlighted: false,
      val: 8,
    },
    {
      id: "hitl",
      label: "Human-in-the-Loop",
      type: "concept",
      description: "Design patterns requiring human oversight of AI decisions",
      source_document: "12_ai_safety_grounding.txt",
      highlighted: false,
      val: 10,
    },
    {
      id: "hybrid_retrieval",
      label: "Hybrid Retrieval",
      type: "technology",
      description:
        "Combining vector similarity with graph traversal for comprehensive search",
      source_document: "08_retrieval_architectures.txt",
      highlighted: false,
      val: 11,
    },
    {
      id: "factscore",
      label: "FActScore",
      type: "technology",
      description:
        "Metric for fine-grained atomic claim verification in AI outputs",
      source_document: "05_citation_grounded_ai.txt",
      highlighted: false,
      val: 7,
    },
    {
      id: "microsoft_graphrag",
      label: "Microsoft GraphRAG",
      type: "technology",
      description:
        "Open-source GraphRAG implementation with community summarization",
      source_document: "01_graphrag_overview.txt",
      highlighted: false,
      val: 10,
    },
    {
      id: "brighton_collaboration",
      label: "Brighton Collaboration",
      type: "organization",
      description:
        "Organization developing standardized case definitions for adverse events following immunization",
      source_document: "03_vaccine_safety_monitoring.txt",
      highlighted: false,
      val: 7,
    },
    {
      id: "traceability",
      label: "Traceability",
      type: "concept",
      description: "Ability to trace AI outputs back to their source evidence",
      source_document: "05_citation_grounded_ai.txt",
      highlighted: false,
      val: 13,
    },
    {
      id: "mayo_clinic",
      label: "Mayo Clinic",
      type: "organization",
      description:
        "Healthcare organization investing in knowledge graph infrastructure",
      source_document: "02_knowledge_graphs_healthcare.txt",
      highlighted: false,
      val: 6,
    },
    {
      id: "fda",
      label: "FDA",
      type: "organization",
      description:
        "US Food and Drug Administration regulating clinical decision support",
      source_document: "10_eu_ai_act_compliance.txt",
      highlighted: false,
      val: 8,
    },
    {
      id: "gnn",
      label: "Graph Neural Networks",
      type: "technology",
      description:
        "Neural networks operating on graph-structured data for signal detection",
      source_document: "03_vaccine_safety_monitoring.txt",
      highlighted: false,
      val: 7,
    },
  ],
  links: [
    {
      source: "graphrag",
      target: "knowledge_graph",
      label: "builds upon",
      weight: 1.0,
      highlighted: false,
    },
    {
      source: "graphrag",
      target: "vector_rag",
      label: "extends",
      weight: 0.9,
      highlighted: false,
    },
    {
      source: "graphrag",
      target: "hallucination",
      label: "reduces",
      weight: 1.0,
      highlighted: false,
    },
    {
      source: "graphrag",
      target: "citation_grounding",
      label: "enables",
      weight: 1.0,
      highlighted: false,
    },
    {
      source: "graphrag",
      target: "hybrid_retrieval",
      label: "uses",
      weight: 0.9,
      highlighted: false,
    },
    {
      source: "knowledge_graph",
      target: "entity_extraction",
      label: "constructed by",
      weight: 1.0,
      highlighted: false,
    },
    {
      source: "knowledge_graph",
      target: "community_detection",
      label: "organized by",
      weight: 0.8,
      highlighted: false,
    },
    {
      source: "knowledge_graph",
      target: "neo4j",
      label: "stored in",
      weight: 0.7,
      highlighted: false,
    },
    {
      source: "community_detection",
      target: "leiden_algorithm",
      label: "implements",
      weight: 0.9,
      highlighted: false,
    },
    {
      source: "citation_grounding",
      target: "traceability",
      label: "provides",
      weight: 1.0,
      highlighted: false,
    },
    {
      source: "citation_grounding",
      target: "factscore",
      label: "measured by",
      weight: 0.7,
      highlighted: false,
    },
    {
      source: "eu_ai_act",
      target: "traceability",
      label: "mandates",
      weight: 1.0,
      highlighted: false,
    },
    {
      source: "eu_ai_act",
      target: "hitl",
      label: "requires",
      weight: 0.9,
      highlighted: false,
    },
    {
      source: "vaccine_safety",
      target: "vaers",
      label: "monitored by",
      weight: 1.0,
      highlighted: false,
    },
    {
      source: "vaccine_safety",
      target: "knowledge_graph",
      label: "analyzed using",
      weight: 0.8,
      highlighted: false,
    },
    {
      source: "vaccine_safety",
      target: "brighton_collaboration",
      label: "standardized by",
      weight: 0.7,
      highlighted: false,
    },
    {
      source: "clinical_trials",
      target: "knowledge_graph",
      label: "modeled in",
      weight: 0.8,
      highlighted: false,
    },
    {
      source: "clinical_trials",
      target: "vaccine_safety",
      label: "informs",
      weight: 0.7,
      highlighted: false,
    },
    {
      source: "umls",
      target: "knowledge_graph",
      label: "provides ontology for",
      weight: 0.8,
      highlighted: false,
    },
    {
      source: "lightrag",
      target: "graphrag",
      label: "implements",
      weight: 0.9,
      highlighted: false,
    },
    {
      source: "microsoft_graphrag",
      target: "graphrag",
      label: "implements",
      weight: 0.9,
      highlighted: false,
    },
    {
      source: "hallucination",
      target: "hitl",
      label: "mitigated by",
      weight: 0.8,
      highlighted: false,
    },
    {
      source: "fda",
      target: "vaccine_safety",
      label: "regulates",
      weight: 0.9,
      highlighted: false,
    },
    {
      source: "fda",
      target: "clinical_trials",
      label: "oversees",
      weight: 0.8,
      highlighted: false,
    },
    {
      source: "mayo_clinic",
      target: "knowledge_graph",
      label: "invests in",
      weight: 0.6,
      highlighted: false,
    },
    {
      source: "gnn",
      target: "vaccine_safety",
      label: "detects signals in",
      weight: 0.7,
      highlighted: false,
    },
    {
      source: "hybrid_retrieval",
      target: "vector_rag",
      label: "incorporates",
      weight: 0.8,
      highlighted: false,
    },
    {
      source: "hybrid_retrieval",
      target: "knowledge_graph",
      label: "traverses",
      weight: 0.9,
      highlighted: false,
    },
    {
      source: "entity_extraction",
      target: "hallucination",
      label: "can produce",
      weight: 0.5,
      highlighted: false,
    },
  ],
};
